unit Book;

interface

uses
  MVCFramework.Serializer.Commons,
  MVCFramework.ActiveRecord,
  MVCFramework.Nullables,
  MVCFramework.Commons,
  MVCFramework.SQLGenerators.MySQL,
  System.Generics.Collections;

type
  [MVCNameCase(ncCamelCase)]
  [MVCTable('book')]
  TBook = class(TMVCActiveRecord)
  private
    [MVCTableField('ID', [foPrimaryKey, foAutoGenerated])]
    FId: Integer;
    [MVCTableField('TITLE')]
    FTitle: string;
    [MVCTableField('SYNOPSIS')]
    FSynopsis: string;
  public
    function IsValid: Boolean;
    property Id: Integer read FId write FId;
    property Title: string read FTitle write FTitle;
    property Synopsis: string read FSynopsis write FSynopsis;
  end;

implementation

{ TBook }

function TBook.IsValid: Boolean;
begin
  Result := (Title <> '') and (Synopsis <> '');
end;

end.
